# Generated by Django 4.1.3 on 2022-11-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quistion_test',
            new_name='question_test',
        ),
    ]
